name: Reusable Build Workflow
on:
  workflow_call:
    inputs:
      release_version:
        required: true
        type: string
      build_matrix:
        required: true
        type: string  # JSON string: e.g., '{"lang":["en","fr","de"],"type":["draft","final"]}'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJSON(inputs.build_matrix) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install fonts
        run: |
          # Create fonts directory
          sudo mkdir -p /usr/share/fonts/truetype/libertinus
          sudo mkdir -p /usr/share/fonts/truetype/fira-sans

          # Download and install Libertinus Serif
          wget -q https://github.com/alerque/libertinus/releases/download/v7.040/Libertinus-7.040.tar.xz
          tar -xf Libertinus-7.040.tar.xz
          sudo cp Libertinus-7.040/static/OTF/LibertinusSerif-*.otf /usr/share/fonts/truetype/libertinus/

          # Download and install Fira Sans
          wget -q https://github.com/mozilla/Fira/archive/refs/tags/4.106.zip -O fira.zip
          unzip -q fira.zip
          sudo cp Fira-4.106/otf/FiraSans-*.otf /usr/share/fonts/truetype/fira-sans/

          # Refresh font cache
          sudo fc-cache -f -v

          # Clean up
          rm -rf Libertinus-7.040* fira.zip Fira-4.106

      - name: Setup Typst
        uses: typst-community/setup-typst@v4

      - name: Install Package
        env:
          RELEASE_VERSION: ${{ inputs.release_version }}
        run: |
          mkdir -p ~/.cache/typst/packages/preview/hei-synd-thesis/${{ env.RELEASE_VERSION }}
          cp -r ./ ~/.cache/typst/packages/preview/hei-synd-thesis/${{ env.RELEASE_VERSION }}

      - name: Build Thesis - ${{ matrix.lang }}/${{ matrix.type }}
        run: typst compile template/thesis.typ template/thesis-${{ inputs.release_version }}-${{ matrix.lang }}_${{ matrix.type }}.pdf --input lang=${{ matrix.lang }} --input type=${{ matrix.type }}

      - name: Upload PDF artifact
        if: ${{ !env.ACT }}
        uses: actions/upload-artifact@v4
        with:
          name: Thesis-${{ inputs.release_version }}-${{ matrix.lang }}_${{ matrix.type }}
          path: template/thesis-${{ inputs.release_version }}-${{ matrix.lang }}_${{ matrix.type }}.pdf
