name: Reusable Build Workflow
on:
  workflow_call:
    inputs:
      release_version:
        required: true
        type: string
      build_matrix:
        required: true
        type: string  # JSON string: e.g., '{"lang":["en","fr","de"],"type":["draft","final"]}'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJSON(inputs.build_matrix) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Typst
        uses: typst-community/setup-typst@v4

      - name: Install Package
        env:
          RELEASE_VERSION: ${{ inputs.release_version }}
        run: |
          mkdir -p ~/.cache/typst/packages/preview/hei-synd-thesis/${{ env.RELEASE_VERSION }}
          cp -r ./ ~/.cache/typst/packages/preview/hei-synd-thesis/${{ env.RELEASE_VERSION }}

      - name: Build Thesis - ${{ matrix.lang }}/${{ matrix.type }}
        run: typst compile template/thesis.typ template/thesis-${{ inputs.release_version }}-${{ matrix.lang }}_${{ matrix.type }}.pdf --input lang=${{ matrix.lang }} --input type=${{ matrix.type }}

      - name: Upload PDF artifact
        if: ${{ !env.ACT }}
        uses: actions/upload-artifact@v4
        with:
          name: Thesis-${{ inputs.release_version }}-${{ matrix.lang }}_${{ matrix.type }}
          path: template/thesis-${{ inputs.release_version }}-${{ matrix.lang }}_${{ matrix.type }}.pdf
